// apps/app-vue/src/App.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";
import { useFrameSDK } from "@zomme/fragment-frame-vue";
import type { User } from "./types";

interface AppProps {
  actionCallback?: (data: any) => void;
  successCallback?: (data: any) => void;
  theme?: "dark" | "light";
  user?: User;
}

const { emit, props, watchProps } = useFrameSDK<AppProps>();
const theme = ref<"dark" | "light">(props.theme || "light");
const user = ref<User | null>(props.user || null);

onMounted(() => {
  console.log("Vue App Component initialized with user:", user.value);

  if (typeof props.successCallback === "function") {
    props.successCallback({ message: "Vue app initialized successfully" });
  }

  document.body.className = theme.value;

  // Watch for theme and user changes with modern API
  const unwatch = watchProps(['theme', 'user'], (changes) => {
    if ('theme' in changes) {
      const [newTheme] = changes.theme;
      console.log("Theme changed:", newTheme);
      theme.value = newTheme as "dark" | "light";
      document.body.className = newTheme as string;
    }

    if ('user' in changes) {
      const [newUser] = changes.user;
      console.log("User updated:", newUser);
      user.value = newUser as User;
    }
  });

  onUnmounted(unwatch);
});

function triggerAction() {
  console.log("Action triggered");

  emit("action-clicked", {
    component: "AppComponent",
    timestamp: Date.now(),
  });

  if (typeof props.actionCallback === "function") {
    props.actionCallback({
      source: "navigation",
      type: "button-click",
    });
  }
}

function triggerError() {
  try {
    throw new Error("Test error from Vue AppComponent");
  } catch (error) {
    console.error("Error triggered:", error);

    emit("error", {
      component: "AppComponent",
      error: error instanceof Error ? error.message : String(error),
      timestamp: Date.now(),
    });
  }
}
</script>

<template>
  <div id="app" class="app-container" :class="theme">
    <nav class="navigation">
      <ul class="nav-menu">
        <li class="nav-item">
          <router-link
            class="nav-link"
            exact-active-class="active"
            to="/"
          >
            Home
          </router-link>
        </li>
        <li class="nav-item">
          <router-link class="nav-link" to="/tasks">
            Tasks
          </router-link>
        </li>
        <li class="nav-item">
          <router-link class="nav-link" to="/analytics">
            Analytics
          </router-link>
        </li>
        <li class="nav-item">
          <router-link class="nav-link" to="/settings">
            Settings
          </router-link>
        </li>
        <li class="nav-item">
          <router-link class="nav-link" to="/about">
            About
          </router-link>
        </li>
        <li class="nav-item">
          <router-link class="nav-link" to="/contact">
            Contact
          </router-link>
        </li>
        <li class="nav-item">
          <button class="demo-btn" @click="triggerAction">
            Test Action
          </button>
        </li>
        <li class="nav-item">
          <button class="demo-btn error-btn" @click="triggerError">
            Test Error
          </button>
        </li>
      </ul>
    </nav>

    <main class="main-content">
      <router-view />
    </main>
  </div>
</template>

<style scoped>
.app-container {
  display: flex;
  flex-direction: column;
  font-family: system-ui, -apple-system, sans-serif;
  height: 100%;
  min-height: 100vh;
  transition: background-color 0.3s;
}

.app-container.light {
  background-color: #f5f5f5;
  color: #333333;
}

.app-container.dark {
  background-color: #1a1a1a;
  color: #eeeeee;
}

.navigation {
  background-color: #42b883;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  padding: 0.5rem 1rem;
}

.nav-menu {
  align-items: center;
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  list-style: none;
  margin: 0;
  padding: 0;
}

.nav-item {
  margin: 0;
}

.nav-link {
  color: white;
  font-weight: 600;
  padding: 0.5rem 1rem;
  text-decoration: none;
  transition: background-color 0.2s;
  border-radius: 6px;
  display: block;
}

.nav-link:hover {
  background-color: rgba(255, 255, 255, 0.1);
}

.nav-link.active {
  background-color: rgba(255, 255, 255, 0.25);
}

.demo-btn {
  background: #35495e;
  color: white;
  border: none;
  padding: 0.5rem 1rem;
  border-radius: 6px;
  cursor: pointer;
  font-size: 0.875rem;
  transition: background-color 0.2s;
  font-weight: 600;
}

.demo-btn:hover {
  background: #2c3e50;
}

.demo-btn.error-btn {
  background: #ef4444;
}

.demo-btn.error-btn:hover {
  background: #dc2626;
}

.main-content {
  flex: 1;
  overflow-y: auto;
}
</style>

// apps/app-react/src/App.tsx
import { type CSSProperties, useEffect, useRef, useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { useFrameSDK } from "@zomme/fragment-frame-react";
import { AppRoutes } from "./router";
import type { User } from "./types";

interface AppProps {
  actionCallback?: (data: any) => void;
  base?: string;
  sdkAvailable?: boolean;
  successCallback?: (data: any) => void;
  theme?: "dark" | "light";
  user?: User;
}

interface FrameProps {
  base?: string;
  sdkAvailable?: boolean;
}

// Module-level flag to track if we've emitted the initial path
// This persists through React StrictMode remounts
let hasEmittedInitialPathGlobal = false;

function App({ sdkAvailable }: FrameProps = {}) {
  const location = useLocation();
  const navigate = useNavigate();
  const { emit, on, props, watchProps } = useFrameSDK<AppProps>();
  const [theme, setTheme] = useState<"dark" | "light">(props.theme || "light");
  const [user, setUser] = useState<User | null>(props.user || null);

  useEffect(() => {
    console.log("React App Component initialized with user:", user);

    if (typeof props.successCallback === "function") {
      props.successCallback({ message: "React app initialized successfully" });
    }

    document.body.className = theme;
  }, []);

  // Listen to route-change events from parent shell
  useEffect(() => {
    if (!sdkAvailable) return;

    const handleRouteChange = (data: any) => {
      const { path } = data as { path: string; replace?: boolean };
      console.log("[React] Received route-change from parent:", path);
      navigate(path, { replace: false });
    };

    const cleanup = on("route-change", handleRouteChange);

    // Return the cleanup function provided by on()
    return cleanup;
  }, [sdkAvailable, on, navigate]);

  // Emit navigation events to parent when route changes (skip initial path)
  useEffect(() => {
    if (!sdkAvailable) return;

    // Skip emitting for the very first path we see (initial load)
    // Use module-level flag to persist through StrictMode remounts
    if (!hasEmittedInitialPathGlobal) {
      hasEmittedInitialPathGlobal = true;
      console.log(
        "[React] Initial path load, skipping navigate event emission for:",
        location.pathname,
      );
      return;
    }

    // location.pathname is already relative to basename, no need to replace
    const path = location.pathname;
    console.log("[React] Emitting navigate event:", path);
    emit("navigate", { path, replace: false, state: {} });
  }, [location.pathname, sdkAvailable, emit]);

  // Watch for theme and user changes with modern API
  useEffect(() => {
    const unwatch = watchProps(['theme', 'user'], (changes) => {
      if ('theme' in changes && changes.theme) {
        const [newTheme] = changes.theme;
        console.log("Theme changed:", newTheme);
        setTheme(newTheme as "dark" | "light");
        document.body.className = newTheme as string;
      }

      if ('user' in changes && changes.user) {
        const [newUser] = changes.user;
        console.log("User updated:", newUser);
        setUser(newUser as User);
      }
    });

    return unwatch;
  }, [watchProps]);

  const triggerAction = () => {
    console.log("Action triggered");

    emit("action-clicked", {
      component: "AppComponent",
      timestamp: Date.now(),
    });

    if (typeof props.actionCallback === "function") {
      props.actionCallback({
        source: "navigation",
        type: "button-click",
      });
    }
  };

  const triggerError = () => {
    try {
      throw new Error("Test error from React AppComponent");
    } catch (error) {
      console.error("Error triggered:", error);

      emit("error", {
        component: "AppComponent",
        error: error instanceof Error ? error.message : String(error),
        timestamp: Date.now(),
      });
    }
  };

  const styles: Record<string, CSSProperties> = {
    appContainer: {
      display: "flex",
      flexDirection: "column",
      fontFamily: "system-ui, -apple-system, sans-serif",
      height: "100%",
      minHeight: "100vh",
      transition: "background-color 0.3s",
    },
    appContainerLight: {
      backgroundColor: "#f5f5f5",
      color: "#333333",
    },
    appContainerDark: {
      backgroundColor: "#1a1a1a",
      color: "#eeeeee",
    },
    navigation: {
      backgroundColor: "#61dafb",
      boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
      padding: "0.5rem 1rem",
    },
    navMenu: {
      alignItems: "center",
      display: "flex",
      flexWrap: "wrap" as const,
      gap: "0.5rem",
      listStyle: "none",
      margin: 0,
      padding: 0,
    },
    navItem: {
      margin: 0,
    },
    navLink: {
      color: "white",
      fontWeight: 600,
      padding: "0.5rem 1rem",
      textDecoration: "none",
      transition: "background-color 0.2s",
      borderRadius: "6px",
      display: "block",
      lineHeight: 1,
    },
    navLinkHover: {
      backgroundColor: "rgba(255, 255, 255, 0.1)",
    },
    navLinkActive: {
      backgroundColor: "rgba(255, 255, 255, 0.25)",
    },
    demoBtn: {
      background: "#35495e",
      color: "white",
      border: "none",
      padding: "0.5rem 1rem",
      borderRadius: "6px",
      cursor: "pointer",
      fontSize: "0.875rem",
      transition: "background-color 0.2s",
      fontWeight: 600,
    },
    demoBtnHover: {
      background: "#2c3e50",
    },
    errorBtn: {
      background: "#ef4444",
    },
    errorBtnHover: {
      background: "#dc2626",
    },
    mainContent: {
      flex: 1,
      overflowY: "auto" as const,
    },
  };

  const containerStyle = {
    ...styles.appContainer,
    ...(theme === "light" ? styles.appContainerLight : styles.appContainerDark),
  };

  return (
    <div id="app" style={containerStyle} className={theme}>
      <nav style={styles.navigation}>
        <ul style={styles.navMenu}>
          <li style={styles.navItem}>
            <Link
              to="/"
              style={{
                ...styles.navLink,
                ...(location.pathname === "/" ? styles.navLinkActive : {}),
              }}
            >
              Home
            </Link>
          </li>
          <li style={styles.navItem}>
            <Link
              to="/tasks"
              style={{
                ...styles.navLink,
                ...(location.pathname === "/tasks" ? styles.navLinkActive : {}),
              }}
            >
              Tasks
            </Link>
          </li>
          <li style={styles.navItem}>
            <Link
              to="/analytics"
              style={{
                ...styles.navLink,
                ...(location.pathname === "/analytics" ? styles.navLinkActive : {}),
              }}
            >
              Analytics
            </Link>
          </li>
          <li style={styles.navItem}>
            <Link
              to="/settings"
              style={{
                ...styles.navLink,
                ...(location.pathname === "/settings" ? styles.navLinkActive : {}),
              }}
            >
              Settings
            </Link>
          </li>
          <li style={styles.navItem}>
            <Link
              to="/about"
              style={{
                ...styles.navLink,
                ...(location.pathname === "/about" ? styles.navLinkActive : {}),
              }}
            >
              About
            </Link>
          </li>
          <li style={styles.navItem}>
            <Link
              to="/contact"
              style={{
                ...styles.navLink,
                ...(location.pathname === "/contact" ? styles.navLinkActive : {}),
              }}
            >
              Contact
            </Link>
          </li>
          <li style={styles.navItem}>
            <button style={styles.demoBtn} onClick={triggerAction}>
              Test Action
            </button>
          </li>
          <li style={styles.navItem}>
            <button style={{ ...styles.demoBtn, ...styles.errorBtn }} onClick={triggerError}>
              Test Error
            </button>
          </li>
        </ul>
      </nav>

      <main style={styles.mainContent}>
        <AppRoutes />
      </main>
    </div>
  );
}

export default App;
