// apps/app-react/src/pages/About.tsx
import { CSSProperties } from "react";
import { version } from "react";
import { PageLayout } from "../components/PageLayout";
import { useFrameSDK } from "@zomme/fragment-frame-react";

export default function About() {
  const { props } = useFrameSDK();
  const reactVersion = version;
  const basePath = (props as any).base || "/react/";
  const apiUrl = (props as any).apiUrl || "Not configured";

  const styles: Record<string, CSSProperties> = {
    section: {
      background: "white",
      borderRadius: "8px",
      boxShadow: "0 2px 8px rgba(0, 0, 0, 0.05)",
      padding: "1.5rem",
    },
    sectionH2: {
      color: "#2c3e50",
      fontSize: "1.5rem",
      marginBottom: "1rem",
    },
    sectionP: {
      color: "#666",
      lineHeight: 1.6,
    },
    list: {
      color: "#666",
      lineHeight: 1.8,
      paddingLeft: "1.5rem",
    },
    benefitsList: {
      color: "#666",
      lineHeight: 1.8,
      paddingLeft: "1.5rem",
    },
    benefitsListLi: {
      marginBottom: "0.5rem",
    },
    infoBox: {
      background: "linear-gradient(135deg, #61dafb 0%, #21a1c4 100%)",
      borderRadius: "8px",
      color: "white",
      padding: "1.5rem",
    },
    infoBoxH3: {
      fontSize: "1.25rem",
      marginBottom: "1rem",
    },
    infoList: {
      display: "grid",
      gap: "0.75rem",
      gridTemplateColumns: "auto 1fr",
    },
    infoListDt: {
      fontWeight: 600,
      opacity: 0.9,
    },
    infoListDd: {
      margin: 0,
    },
  };

  return (
    <PageLayout
      title="About This Application"
      subtitle="Learn about the React micro-frontend architecture and technologies"
    >
      <section style={styles.section}>
          <h2 style={styles.sectionH2}>React 18 Micro-Frontend</h2>
          <p style={styles.sectionP}>
            This application is built as a micro-frontend using React 18 and demonstrates the power
            of modern web architecture patterns. It runs independently while seamlessly integrating
            with a host application through a shared SDK.
          </p>
        </section>

        <section style={styles.section}>
          <h2 style={styles.sectionH2}>Key Technologies</h2>
          <ul style={styles.list}>
            <li>React 18 with Hooks</li>
            <li>React Router for navigation</li>
            <li>TypeScript for type safety</li>
            <li>Vite for fast development and optimized builds</li>
            <li>Micro-Frontend SDK for host communication</li>
          </ul>
        </section>

        <section style={styles.section}>
          <h2 style={styles.sectionH2}>Architecture Benefits</h2>
          <ul style={styles.benefitsList}>
            <li style={styles.benefitsListLi}>
              <strong>Independent Development:</strong> Teams can work autonomously
            </li>
            <li style={styles.benefitsListLi}>
              <strong>Technology Agnostic:</strong> Mix different frameworks
            </li>
            <li style={styles.benefitsListLi}>
              <strong>Scalability:</strong> Scale teams and features independently
            </li>
            <li style={styles.benefitsListLi}>
              <strong>Deployment:</strong> Deploy micro-apps separately
            </li>
          </ul>
        </section>

        <div style={styles.infoBox}>
          <h3 style={styles.infoBoxH3}>Application Info</h3>
          <dl style={styles.infoList}>
            <dt style={styles.infoListDt}>Framework:</dt>
            <dd style={styles.infoListDd}>React {reactVersion}</dd>
            <dt style={styles.infoListDt}>Base Path:</dt>
            <dd style={styles.infoListDd}>{basePath}</dd>
            <dt style={styles.infoListDt}>API URL:</dt>
            <dd style={styles.infoListDd}>{apiUrl}</dd>
          </dl>
        </div>
    </PageLayout>
  );
}

// apps/app-vue/src/views/About.vue
<script setup lang="ts">
import { computed, version } from "vue";
import { useFrameSDK } from "@zomme/fragment-frame-vue";
import PageLayout from "../components/PageLayout.vue";

const { props } = useFrameSDK();
const vueVersion = version;
const basePath = computed(() => props.base || "/vue/");
const apiUrl = computed(() => (props as any).apiUrl || "Not configured");
</script>

<template>
  <PageLayout subtitle="Learn about Vue 3 Micro-Frontend Architecture" title="About This Application">
      <section class="section">
        <h2>Vue 3 Micro-Frontend</h2>
        <p>
          This application is built as a micro-frontend using Vue 3 and demonstrates
          the power of modern web architecture patterns. It runs independently while
          seamlessly integrating with a host application through a shared SDK.
        </p>
      </section>

      <section class="section">
        <h2>Key Technologies</h2>
        <ul class="tech-list">
          <li>Vue 3 with Composition API</li>
          <li>Vue Router for navigation</li>
          <li>TypeScript for type safety</li>
          <li>Vite for fast development and optimized builds</li>
          <li>Micro-Frontend SDK for host communication</li>
        </ul>
      </section>

      <section class="section">
        <h2>Architecture Benefits</h2>
        <ul class="benefits-list">
          <li><strong>Independent Development:</strong> Teams can work autonomously</li>
          <li><strong>Technology Agnostic:</strong> Mix different frameworks</li>
          <li><strong>Scalability:</strong> Scale teams and features independently</li>
          <li><strong>Deployment:</strong> Deploy micro-apps separately</li>
        </ul>
      </section>

      <div class="info-box">
        <h3>Application Info</h3>
        <dl class="info-list">
          <dt>Framework:</dt>
          <dd>Vue {{ vueVersion }}</dd>
          <dt>Base Path:</dt>
          <dd>{{ basePath }}</dd>
          <dt>API URL:</dt>
          <dd>{{ apiUrl || 'Not configured' }}</dd>
        </dl>
      </div>
  </PageLayout>
</template>

<style scoped>
  .section {
    background: white;
    border-radius: 8px;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
    padding: 1.5rem;
  }

  .section h2 {
    color: #1a1a1a;
    font-size: 1.25rem;
    margin: 0 0 1rem;
  }

  .section p {
    color: #666;
    line-height: 1.6;
  }

  .tech-list,
  .benefits-list {
    color: #666;
    line-height: 1.8;
    padding-left: 1.5rem;
  }

  .benefits-list li {
    margin-bottom: 0.5rem;
  }

  .info-box {
    background: linear-gradient(135deg, #42b883 0%, #35495e 100%);
    border-radius: 8px;
    color: white;
    padding: 1.5rem;
  }

  .info-box h3 {
    font-size: 1.25rem;
    margin-bottom: 1rem;
  }

  .info-list {
    display: grid;
    gap: 0.75rem;
    grid-template-columns: auto 1fr;
  }

  .info-list dt {
    font-weight: 600;
    opacity: 0.9;
  }

  .info-list dd {
    margin: 0;
  }
</style>
