// apps/app-react/src/pages/Contact.tsx
import { useState } from "react";
import { PageLayout } from "../components/PageLayout";
import { useFrameSDK } from "@zomme/fragment-frame-react";

export default function Contact() {
  const { emit } = useFrameSDK();
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    subject: "",
    message: "",
  });
  const [submitMessage, setSubmitMessage] = useState("");
  const [submitSuccess, setSubmitSuccess] = useState(false);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitMessage("Message sent successfully! (This is a demo)");
    setSubmitSuccess(true);

    emit("contact-form-submitted", {
      ...formData,
      timestamp: new Date().toISOString(),
    });

    setTimeout(() => {
      setSubmitMessage("");
      setFormData({
        name: "",
        email: "",
        subject: "",
        message: "",
      });
    }, 3000);
  };

  return (
    <PageLayout
      title="Contact Us"
      subtitle="Get in touch with questions or feedback about the React micro-frontend"
    >
      <div className="content-grid">
        <div className="grid-item">
          <div
            style={{
              background: "var(--bg-secondary)",
              borderRadius: "var(--radius-md)",
              padding: "2rem",
              border: "1px solid var(--border-color)",
            }}
          >
            <p
              style={{
                color: "var(--text-secondary)",
                lineHeight: 1.6,
                marginBottom: "2rem",
              }}
            >
              Have questions about our React micro-frontend? Fill out the form below and we'll get
              back to you.
            </p>

            <form
              onSubmit={handleSubmit}
              style={{ display: "flex", flexDirection: "column", gap: "1.5rem" }}
            >
              <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
                <label
                  htmlFor="name"
                  style={{
                    color: "var(--text-primary)",
                    fontWeight: 600,
                  }}
                >
                  Name
                </label>
                <input
                  type="text"
                  id="name"
                  name="name"
                  value={formData.name}
                  onChange={handleChange}
                  placeholder="Your name"
                  required
                  className="form-input"
                />
              </div>

              <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
                <label
                  htmlFor="email"
                  style={{
                    color: "var(--text-primary)",
                    fontWeight: 600,
                  }}
                >
                  Email
                </label>
                <input
                  type="email"
                  id="email"
                  name="email"
                  value={formData.email}
                  onChange={handleChange}
                  placeholder="your.email@example.com"
                  required
                  className="form-input"
                />
              </div>

              <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
                <label
                  htmlFor="subject"
                  style={{
                    color: "var(--text-primary)",
                    fontWeight: 600,
                  }}
                >
                  Subject
                </label>
                <input
                  type="text"
                  id="subject"
                  name="subject"
                  value={formData.subject}
                  onChange={handleChange}
                  placeholder="What's this about?"
                  required
                  className="form-input"
                />
              </div>

              <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
                <label
                  htmlFor="message"
                  style={{
                    color: "var(--text-primary)",
                    fontWeight: 600,
                  }}
                >
                  Message
                </label>
                <textarea
                  id="message"
                  name="message"
                  value={formData.message}
                  onChange={handleChange}
                  placeholder="Your message here..."
                  required
                  rows={6}
                  className="form-input"
                  style={{ resize: "vertical" }}
                />
              </div>

              <button
                type="submit"
                style={{
                  backgroundColor: "#61dafb",
                  border: "none",
                  borderRadius: "4px",
                  color: "white",
                  cursor: "pointer",
                  fontSize: "1rem",
                  fontWeight: 600,
                  padding: "0.875rem 1.5rem",
                  transition: "background-color 0.2s",
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.backgroundColor = "#21a1c4";
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.backgroundColor = "#61dafb";
                }}
              >
                Send Message
              </button>
            </form>

            {submitMessage && (
              <div
                style={{
                  marginTop: "1rem",
                  padding: "1rem",
                  borderRadius: "4px",
                  backgroundColor: submitSuccess ? "#f0fdf4" : "#f0f9ff",
                  borderLeft: `4px solid ${submitSuccess ? "#61dafb" : "#3b82f6"}`,
                  color: submitSuccess ? "#166534" : "#1e40af",
                }}
              >
                {submitMessage}
              </div>
            )}
          </div>
        </div>

        <div
          className="grid-item"
          style={{ display: "flex", flexDirection: "column", gap: "1.5rem" }}
        >
          <h2 style={{ color: "#2c3e50", fontSize: "1.5rem" }}>
            Other Ways to Reach Us
          </h2>

          <div
            style={{
              background: "white",
              borderRadius: "8px",
              padding: "1.5rem",
              boxShadow: "0 2px 8px rgba(0, 0, 0, 0.05)",
            }}
          >
            <h3
              style={{
                color: "#61dafb",
                fontSize: "1.125rem",
                marginBottom: "0.5rem",
              }}
            >
              Email
            </h3>
            <p style={{ color: "#666", margin: 0 }}>support@react-microapp.com</p>
          </div>

          <div
            style={{
              background: "white",
              borderRadius: "8px",
              padding: "1.5rem",
              boxShadow: "0 2px 8px rgba(0, 0, 0, 0.05)",
            }}
          >
            <h3
              style={{
                color: "#61dafb",
                fontSize: "1.125rem",
                marginBottom: "0.5rem",
              }}
            >
              Documentation
            </h3>
            <p style={{ color: "#666", margin: 0 }}>
              Visit our docs for detailed guides
            </p>
          </div>

          <div
            style={{
              background: "white",
              borderRadius: "8px",
              padding: "1.5rem",
              boxShadow: "0 2px 8px rgba(0, 0, 0, 0.05)",
            }}
          >
            <h3
              style={{
                color: "#61dafb",
                fontSize: "1.125rem",
                marginBottom: "0.5rem",
              }}
            >
              GitHub
            </h3>
            <p style={{ color: "#666", margin: 0 }}>
              Check out our open source repository
            </p>
          </div>
        </div>
      </div>
    </PageLayout>
  );
}

// apps/app-vue/src/views/Contact.vue
<script setup lang="ts">
import { reactive, ref } from "vue";
import { useFrameSDK } from "@zomme/fragment-frame-vue";
import PageLayout from "../components/PageLayout.vue";

const { emit } = useFrameSDK();

const formData = reactive({
  email: "",
  message: "",
  name: "",
  subject: "",
});

const submitMessage = ref("");
const submitSuccess = ref(false);

function handleSubmit() {
  submitMessage.value = "Message sent successfully! (This is a demo)";
  submitSuccess.value = true;

  emit("contact-form-submitted", {
    ...formData,
    timestamp: new Date().toISOString(),
  });

  setTimeout(() => {
    submitMessage.value = "";
    Object.keys(formData).forEach((key) => {
      formData[key as keyof typeof formData] = "";
    });
  }, 3000);
}
</script>

<template>
  <PageLayout subtitle="Get in touch with our team" title="Contact Us">
      <div class="form-section">
        <p class="intro">
          Have questions about our Vue micro-frontend? Fill out the form below and we'll get back to you.
        </p>

        <form class="contact-form" @submit.prevent="handleSubmit">
          <div class="form-group">
            <label class="form-label" for="name">Name</label>
            <input
              id="name"
              v-model="formData.name"
              class="form-input"
              placeholder="Your name"
              required
              type="text"
            />
          </div>

          <div class="form-group">
            <label class="form-label" for="email">Email</label>
            <input
              id="email"
              v-model="formData.email"
              class="form-input"
              placeholder="your.email@example.com"
              required
              type="email"
            />
          </div>

          <div class="form-group">
            <label class="form-label" for="subject">Subject</label>
            <input
              id="subject"
              v-model="formData.subject"
              class="form-input"
              placeholder="What's this about?"
              required
              type="text"
            />
          </div>

          <div class="form-group">
            <label class="form-label" for="message">Message</label>
            <textarea
              id="message"
              v-model="formData.message"
              class="form-textarea"
              placeholder="Your message here..."
              required
              rows="6"
            ></textarea>
          </div>

          <button class="submit-button" type="submit">
            Send Message
          </button>
        </form>

        <div v-if="submitMessage" class="submit-message" :class="{ success: submitSuccess }">
          {{ submitMessage }}
        </div>
      </div>

      <div class="info-section">
        <h2>Other Ways to Reach Us</h2>
        <div class="contact-methods">
          <div class="contact-method">
            <h3>Email</h3>
            <p>support@vue-microapp.com</p>
          </div>
          <div class="contact-method">
            <h3>Documentation</h3>
            <p>Visit our docs for detailed guides</p>
          </div>
          <div class="contact-method">
            <h3>GitHub</h3>
            <p>Check out our open source repository</p>
          </div>
        </div>
      </div>
  </PageLayout>
</template>

<style scoped>
  :deep(.content) {
    display: grid;
    gap: 2rem;
    grid-template-columns: 1fr 1fr;
  }

  @media (max-width: 768px) {
    .content {
      grid-template-columns: 1fr;
    }
  }

  .form-section {
    background: white;
    border-radius: 8px;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
    padding: 2rem;
  }

  .intro {
    color: #666;
    line-height: 1.6;
    margin-bottom: 2rem;
  }

  .contact-form {
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
  }

  .form-group {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }

  .form-label {
    color: #2c3e50;
    font-weight: 600;
  }

  .form-input,
  .form-textarea {
    border: 1px solid #ddd;
    border-radius: 4px;
    font-family: inherit;
    font-size: 1rem;
    padding: 0.75rem;
    transition: border-color 0.2s;
  }

  .form-input:focus,
  .form-textarea:focus {
    border-color: #42b883;
    outline: none;
  }

  .form-textarea {
    resize: vertical;
  }

  .submit-button {
    background-color: #42b883;
    border: none;
    border-radius: 4px;
    color: white;
    cursor: pointer;
    font-size: 1rem;
    font-weight: 600;
    padding: 0.875rem 1.5rem;
    transition: background-color 0.2s;
  }

  .submit-button:hover {
    background-color: #359268;
  }

  .submit-message {
    background-color: #f0f9ff;
    border-left: 4px solid #3b82f6;
    border-radius: 4px;
    color: #1e40af;
    margin-top: 1rem;
    padding: 1rem;
  }

  .submit-message.success {
    background-color: #f0fdf4;
    border-left-color: #42b883;
    color: #166534;
  }

  .info-section {
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
  }

  .info-section h2 {
    color: #1a1a1a;
    font-size: 1.25rem;
    margin: 0 0 1rem;
  }

  .contact-methods {
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
  }

  .contact-method {
    background: white;
    border-radius: 8px;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
    padding: 1.5rem;
  }

  .contact-method h3 {
    color: #42b883;
    font-size: 1.125rem;
    margin-bottom: 0.5rem;
  }

  .contact-method p {
    color: #666;
    line-height: 1.5;
    margin: 0;
  }
</style>
