// apps/app-react/src/pages/Home.tsx
import { CSSProperties, useEffect, useRef, useState } from "react";
import { version } from "react";
import { Link } from "react-router-dom";
import { PageLayout } from "../components/PageLayout";
import { useFrameSDK } from "@zomme/fragment-frame-react";

interface HomeProps {
  actionCallback?: (data: any) => void;
  apiUrl?: string;
  base?: string;
  theme?: "dark" | "light";
}

function Home() {
  const { emit, props } = useFrameSDK<HomeProps>();
  const reactVersion = version;
  const basePath = props.base || "/react/";
  const apiUrl = props.apiUrl || "Not configured";

  const [theme, setTheme] = useState<"dark" | "light">(props.theme || "light");
  const [saveMessage, setSaveMessage] = useState("");
  const timeoutRef = useRef<NodeJS.Timeout | null>(null);

  useEffect(() => {
    if (props.theme) {
      setTheme(props.theme);
    }
  }, [props.theme]);

  useEffect(() => {
    return () => {
      if (timeoutRef.current) {
        clearTimeout(timeoutRef.current);
      }
    };
  }, []);

  function handleEmitEvent() {
    emit("custom-event", {
      message: "Hello from React Task Dashboard!",
      timestamp: new Date().toISOString(),
    });
  }

  const triggerActionCallback = () => {
    if (typeof props.actionCallback === "function") {
      props.actionCallback({
        component: "Home",
        source: "callback-demo",
        timestamp: Date.now(),
        type: "test-action",
      });

      setSaveMessage("Action callback triggered!");

      timeoutRef.current = setTimeout(() => {
        setSaveMessage("");
      }, 2000);
    } else {
      setSaveMessage("No action callback provided");

      timeoutRef.current = setTimeout(() => {
        setSaveMessage("");
      }, 2000);
    }
  };

  const testThemeToggle = () => {
    const newTheme = theme === "light" ? "dark" : "light";
    emit("change-theme", { theme: newTheme });
  };

  return (
    <PageLayout
      title="Welcome to React Task Dashboard"
      subtitle="A comprehensive demonstration of fragment-elements SDK capabilities using React 18 and modern micro-frontend patterns"
    >
      <div style={styles.infoCard}>
        <h3 style={styles.infoCardH3}>Props from Parent</h3>
        <pre style={styles.infoCardPre}>{JSON.stringify(props, null, 2)}</pre>
      </div>

      <div style={styles.features}>
        <div style={styles.featureCard}>
          <div style={styles.featureIcon}>📋</div>
          <h3 style={styles.featureCardH3}>Task Management</h3>
          <p style={styles.featureCardP}>Props + Events + Search functionality</p>
          <Link style={styles.featureLink} to="/tasks">
            View Tasks →
          </Link>
        </div>

        <div style={styles.featureCard}>
          <div style={styles.featureIcon}>📊</div>
          <h3 style={styles.featureCardH3}>Analytics Dashboard</h3>
          <p style={styles.featureCardP}>Transferable Objects with ArrayBuffer</p>
          <Link style={styles.featureLink} to="/analytics">
            View Analytics →
          </Link>
        </div>

        <div style={styles.featureCard}>
          <div style={styles.featureIcon}>⚙️</div>
          <h3 style={styles.featureCardH3}>Settings</h3>
          <p style={styles.featureCardP}>Async Callbacks + Attribute Listeners</p>
          <Link style={styles.featureLink} to="/settings">
            View Settings →
          </Link>
        </div>
      </div>

      <div style={styles.demoSection}>
        <h3 style={styles.demoSectionH3}>SDK Features Demonstrated</h3>
        <ul style={styles.featureList}>
          <li style={styles.featureListLi}>
            <strong style={styles.featureListStrong}>Props Access:</strong> Read initial props from
            parent
          </li>
          <li style={styles.featureListLi}>
            <strong style={styles.featureListStrong}>Event Emission:</strong> Emit events to parent
            shell
          </li>
          <li style={styles.featureListLi}>
            <strong style={styles.featureListStrong}>Event Listeners:</strong> Listen to events from
            parent
          </li>
          <li style={styles.featureListLi}>
            <strong style={styles.featureListStrong}>Attribute Listeners:</strong> React to
            attribute changes
          </li>
          <li style={styles.featureListLi}>
            <strong style={styles.featureListStrong}>Callbacks:</strong> Execute parent functions
          </li>
          <li style={styles.featureListLi}>
            <strong style={styles.featureListStrong}>Async Callbacks:</strong> Handle promises from
            parent
          </li>
          <li style={styles.featureListLi}>
            <strong style={styles.featureListStrong}>Transferable Objects:</strong> Efficient
            ArrayBuffer transfer
          </li>
          <li style={styles.featureListLi}>
            <strong style={styles.featureListStrong}>Navigation:</strong> Synchronized routing with
            parent
          </li>
          <li style={styles.featureListLi}>
            <strong style={styles.featureListStrong}>Error Handling:</strong> Proper error
            propagation
          </li>
          <li style={styles.featureListLi}>
            <strong style={styles.featureListStrong}>Cleanup:</strong> Memory leak prevention
          </li>
        </ul>
      </div>

      <div style={styles.actions}>
        <button style={styles.actionBtn} type="button" onClick={handleEmitEvent}>
          Emit Custom Event
        </button>
      </div>

      <section style={styles.section}>
        <h2 style={styles.sectionH2}>React 18 Micro-Frontend</h2>
        <p style={styles.sectionP}>
          This application is built as a micro-frontend using React 18 and demonstrates the power
          of modern web architecture patterns. It runs independently while seamlessly integrating
          with a host application through a shared SDK.
        </p>
      </section>

      <section style={styles.section}>
        <h2 style={styles.sectionH2}>Key Technologies</h2>
        <ul style={styles.list}>
          <li>React 18 with Hooks</li>
          <li>React Router for navigation</li>
          <li>TypeScript for type safety</li>
          <li>Vite for fast development and optimized builds</li>
          <li>Micro-Frontend SDK for host communication</li>
        </ul>
      </section>

      <section style={styles.section}>
        <h2 style={styles.sectionH2}>Architecture Benefits</h2>
        <ul style={styles.benefitsList}>
          <li style={styles.benefitsListLi}>
            <strong>Independent Development:</strong> Teams can work autonomously
          </li>
          <li style={styles.benefitsListLi}>
            <strong>Technology Agnostic:</strong> Mix different frameworks
          </li>
          <li style={styles.benefitsListLi}>
            <strong>Scalability:</strong> Scale teams and features independently
          </li>
          <li style={styles.benefitsListLi}>
            <strong>Deployment:</strong> Deploy micro-apps separately
          </li>
        </ul>
      </section>

      <section style={styles.sdkDemoSection}>
        <h2 style={styles.sdkDemoSectionH2}>SDK Demonstrations</h2>

        <div style={styles.sdkInfoCard}>
          <h3 style={styles.sdkInfoCardH3}>About This Demo</h3>
          <p style={styles.sdkInfoCardP}>
            This page demonstrates <strong>Async Callbacks</strong> and{" "}
            <strong>Attribute Listeners</strong>:
          </p>
          <ul style={styles.sdkInfoCardUl}>
            <li style={styles.sdkInfoCardLi}>
              Settings can be saved using an async callback function passed from parent
            </li>
            <li style={styles.sdkInfoCardLi}>Theme changes are detected via attribute listeners</li>
            <li style={styles.sdkInfoCardLi}>User data updates are synchronized automatically</li>
          </ul>
        </div>

        <div style={styles.callbackDemo}>
          <h3 style={styles.callbackDemoH3}>Callback Demo</h3>
          <p style={styles.callbackDemoP}>
            Test synchronous callback functions passed from parent:
          </p>
          <button style={styles.demoBtn} type="button" onClick={triggerActionCallback}>
            Trigger Action Callback
          </button>
        </div>

        <div style={styles.attrListenerDemo}>
          <h3 style={styles.attrListenerDemoH3}>Attribute Listener Demo</h3>
          <p style={styles.attrListenerDemoP}>
            Request theme change from parent (will trigger attribute listener):
          </p>
          <div style={styles.themeDemo}>
            <div
              style={
                theme === "light"
                  ? { ...styles.themeIndicator, ...styles.themeIndicatorLight }
                  : { ...styles.themeIndicator, ...styles.themeIndicatorDark }
              }
            >
              Current theme: <strong>{theme}</strong>
            </div>
            <button style={styles.demoBtn} type="button" onClick={testThemeToggle}>
              Request Theme Toggle
            </button>
          </div>
        </div>

        <div style={styles.techDetails}>
          <h4 style={styles.techDetailsH4}>Technical Details</h4>
          <ul style={styles.techDetailsUl}>
            <li style={styles.techDetailsLi}>
              <strong style={styles.techDetailsStrong}>Async Callbacks:</strong> saveCallback
              returns a Promise with result
            </li>
            <li style={styles.techDetailsLi}>
              <strong style={styles.techDetailsStrong}>Attribute Listeners:</strong>{" "}
              onAttr('theme', handler) detects changes
            </li>
            <li style={styles.techDetailsLi}>
              <strong style={styles.techDetailsStrong}>Bidirectional:</strong> Fragment can
              request changes via events
            </li>
            <li style={styles.techDetailsLi}>
              <strong style={styles.techDetailsStrong}>Type Safety:</strong> TypeScript interfaces
              ensure correct usage
            </li>
          </ul>
        </div>

        {saveMessage && <div style={styles.message}>{saveMessage}</div>}
      </section>

      <div style={styles.appInfoBox}>
        <h3 style={styles.appInfoBoxH3}>Application Info</h3>
        <dl style={styles.appInfoList}>
          <dt style={styles.appInfoListDt}>Framework:</dt>
          <dd style={styles.appInfoListDd}>React {reactVersion}</dd>
          <dt style={styles.appInfoListDt}>Base Path:</dt>
          <dd style={styles.appInfoListDd}>{basePath}</dd>
          <dt style={styles.appInfoListDt}>API URL:</dt>
          <dd style={styles.appInfoListDd}>{apiUrl}</dd>
        </dl>
      </div>
    </PageLayout>
  );
}

const styles: Record<string, CSSProperties> = {
  infoCard: {
    background: "#f8f9fa",
    border: "1px solid #dee2e6",
    borderRadius: "8px",
    padding: "1.5rem",
    marginBottom: "2rem",
  },
  infoCardH3: {
    margin: "0 0 1rem",
    color: "#495057",
    fontSize: "1.125rem",
  },
  infoCardPre: {
    background: "white",
    padding: "1rem",
    borderRadius: "4px",
    overflowX: "auto",
    fontSize: "0.875rem",
    margin: "0",
  },
  features: {
    display: "grid",
    gap: "1.5rem",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    marginBottom: "2rem",
  },
  featureCard: {
    background: "white",
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
    padding: "1.5rem",
    transition: "all 0.2s",
  },
  featureIcon: {
    fontSize: "2.5rem",
    marginBottom: "1rem",
  },
  featureCardH3: {
    color: "#1a1a1a",
    fontSize: "1.25rem",
    margin: "0 0 0.5rem",
  },
  featureCardP: {
    color: "#666",
    lineHeight: "1.5",
    margin: "0 0 1rem",
  },
  featureLink: {
    color: "#61dafb",
    textDecoration: "none",
    fontWeight: 600,
    transition: "color 0.2s",
  },
  demoSection: {
    background: "white",
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
    padding: "1.5rem",
    marginBottom: "2rem",
  },
  demoSectionH3: {
    margin: "0 0 1rem",
    color: "#1a1a1a",
    fontSize: "1.25rem",
  },
  featureList: {
    margin: "0",
    paddingLeft: "1.5rem",
    listStyle: "disc",
  },
  featureListLi: {
    color: "#666",
    lineHeight: "1.8",
    marginBottom: "0.5rem",
  },
  featureListStrong: {
    color: "#1a1a1a",
  },
  actions: {
    display: "flex",
    gap: "1rem",
    marginBottom: "2rem",
  },
  actionBtn: {
    padding: "0.875rem 1.5rem",
    background: "#61dafb",
    color: "white",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "0.875rem",
    fontWeight: 600,
    transition: "background 0.2s",
  },
  section: {
    background: "white",
    borderRadius: "8px",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.05)",
    padding: "1.5rem",
    marginBottom: "2rem",
  },
  sectionH2: {
    color: "#2c3e50",
    fontSize: "1.5rem",
    marginBottom: "1rem",
  },
  sectionP: {
    color: "#666",
    lineHeight: 1.6,
  },
  list: {
    color: "#666",
    lineHeight: 1.8,
    paddingLeft: "1.5rem",
  },
  benefitsList: {
    color: "#666",
    lineHeight: 1.8,
    paddingLeft: "1.5rem",
  },
  benefitsListLi: {
    marginBottom: "0.5rem",
  },
  sdkDemoSection: {
    background: "white",
    borderRadius: "8px",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.05)",
    padding: "1.5rem",
    marginBottom: "2rem",
  },
  sdkDemoSectionH2: {
    color: "#2c3e50",
    fontSize: "1.5rem",
    marginBottom: "1rem",
  },
  sdkInfoCard: {
    padding: "1.5rem",
    background: "#fef3c7",
    border: "1px solid #fde68a",
    borderRadius: "8px",
    marginBottom: "1.5rem",
  },
  sdkInfoCardH3: {
    margin: "0 0 0.75rem",
    color: "#92400e",
    fontSize: "1.125rem",
  },
  sdkInfoCardP: {
    margin: "0 0 0.5rem",
    color: "#78350f",
    lineHeight: 1.6,
  },
  sdkInfoCardUl: {
    margin: "0.5rem 0 0",
    paddingLeft: "1.5rem",
    color: "#78350f",
  },
  sdkInfoCardLi: {
    marginBottom: "0.25rem",
  },
  callbackDemo: {
    padding: "1.5rem",
    background: "white",
    borderRadius: "8px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    marginBottom: "1.5rem",
  },
  callbackDemoH3: {
    margin: "0 0 0.75rem",
    fontSize: "1.125rem",
    color: "#1a1a1a",
  },
  callbackDemoP: {
    margin: "0 0 1rem",
    color: "#666",
    fontSize: "0.875rem",
  },
  demoBtn: {
    padding: "0.75rem 1.5rem",
    background: "#3b82f6",
    color: "white",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "0.875rem",
    fontWeight: 600,
    transition: "background 0.2s",
  },
  attrListenerDemo: {
    padding: "1.5rem",
    background: "white",
    borderRadius: "8px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    marginBottom: "1.5rem",
  },
  attrListenerDemoH3: {
    margin: "0 0 0.75rem",
    fontSize: "1.125rem",
    color: "#1a1a1a",
  },
  attrListenerDemoP: {
    margin: "0 0 1rem",
    color: "#666",
    fontSize: "0.875rem",
  },
  themeDemo: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
  },
  themeIndicator: {
    padding: "0.75rem 1rem",
    borderRadius: "6px",
    fontSize: "0.875rem",
  },
  themeIndicatorLight: {
    background: "#f9fafb",
    border: "2px solid #e5e7eb",
    color: "#1a1a1a",
  },
  themeIndicatorDark: {
    background: "#1f2937",
    border: "2px solid #374151",
    color: "#f9fafb",
  },
  techDetails: {
    padding: "1.5rem",
    background: "#f9fafb",
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
    marginBottom: "1.5rem",
  },
  techDetailsH4: {
    margin: "0 0 1rem",
    fontSize: "1rem",
    color: "#1a1a1a",
  },
  techDetailsUl: {
    margin: 0,
    paddingLeft: "1.5rem",
    listStyle: "disc",
  },
  techDetailsLi: {
    marginBottom: "0.5rem",
    color: "#666",
    lineHeight: 1.6,
  },
  techDetailsStrong: {
    color: "#1a1a1a",
  },
  message: {
    padding: "1rem",
    background: "#d1ecf1",
    border: "1px solid #bee5eb",
    borderRadius: "6px",
    color: "#0c5460",
    fontSize: "0.875rem",
    marginTop: "1rem",
  },
  appInfoBox: {
    background: "linear-gradient(135deg, #61dafb 0%, #21a1c4 100%)",
    borderRadius: "8px",
    color: "white",
    padding: "1.5rem",
  },
  appInfoBoxH3: {
    fontSize: "1.25rem",
    marginBottom: "1rem",
  },
  appInfoList: {
    display: "grid",
    gap: "0.75rem",
    gridTemplateColumns: "auto 1fr",
  },
  appInfoListDt: {
    fontWeight: 600,
    opacity: 0.9,
  },
  appInfoListDd: {
    margin: 0,
  },
};

export default Home;

// apps/app-vue/src/views/Home.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, version, watch } from "vue";
import { useFrameSDK } from "@zomme/fragment-frame-vue";
import PageLayout from "../components/PageLayout.vue";

interface HomeProps {
  actionCallback?: (data: any) => void;
  base?: string;
  theme?: "dark" | "light";
}

const { emit, props, watchProps } = useFrameSDK<HomeProps>();
const vueVersion = version;
const basePath = computed(() => props.base || "/vue/");
const apiUrl = computed(() => (props as any).apiUrl || "Not configured");

const theme = ref<"dark" | "light">(props.theme || "light");
const saveMessage = ref("");

onMounted(() => {
  if (props.theme) {
    theme.value = props.theme;
  }

  // Watch for theme changes with modern API
  const unwatch = watchProps(['theme'], (changes) => {
    if ('theme' in changes) {
      const [newTheme] = changes.theme;
      theme.value = newTheme as "dark" | "light";

      emit("theme-changed", {
        source: "watch-listener",
        theme: newTheme,
        timestamp: Date.now(),
      });
    }
  });

  onUnmounted(unwatch);
});

watch(theme, (newTheme) => {
  document.body.classList.remove("light", "dark");
  document.body.classList.add(newTheme);
});

function handleEmitEvent() {
  emit("custom-event", {
    message: "Hello from Vue Task Dashboard!",
    timestamp: new Date().toISOString(),
  });
}

function triggerActionCallback() {
  if (typeof props.actionCallback === "function") {
    props.actionCallback({
      component: "Home",
      source: "callback-demo",
      timestamp: Date.now(),
      type: "test-action",
    });

    saveMessage.value = "Action callback triggered!";

    setTimeout(() => {
      saveMessage.value = "";
    }, 2000);
  } else {
    saveMessage.value = "No action callback provided";

    setTimeout(() => {
      saveMessage.value = "";
    }, 2000);
  }
}

function testThemeToggle() {
  const newTheme = theme.value === "light" ? "dark" : "light";
  emit("change-theme", { theme: newTheme });
}
</script>

<template>
  <PageLayout
    subtitle="A comprehensive demonstration of fragment-elements SDK capabilities using Vue 3 Composition API and modern micro-frontend patterns"
    title="Welcome to Vue Task Dashboard"
  >

    <div class="info-card">
      <h3>Props from Parent</h3>
      <pre>{{ JSON.stringify(props, null, 2) }}</pre>
    </div>

    <div class="features">
      <div class="feature-card">
        <div class="feature-icon">📋</div>
        <h3>Task Management</h3>
        <p>Props + Events + Search functionality</p>
        <router-link class="feature-link" to="/tasks">
          View Tasks →
        </router-link>
      </div>

      <div class="feature-card">
        <div class="feature-icon">📊</div>
        <h3>Analytics Dashboard</h3>
        <p>Transferable Objects with ArrayBuffer</p>
        <router-link class="feature-link" to="/analytics">
          View Analytics →
        </router-link>
      </div>

      <div class="feature-card">
        <div class="feature-icon">⚙️</div>
        <h3>Settings</h3>
        <p>Async Callbacks + Attribute Listeners</p>
        <router-link class="feature-link" to="/settings">
          View Settings →
        </router-link>
      </div>
    </div>

    <div class="demo-section">
      <h3>SDK Features Demonstrated</h3>
      <ul class="feature-list">
        <li><strong>Props Access:</strong> Read initial props from parent</li>
        <li><strong>Event Emission:</strong> Emit events to parent shell</li>
        <li><strong>Event Listeners:</strong> Listen to events from parent</li>
        <li><strong>Attribute Listeners:</strong> React to attribute changes</li>
        <li><strong>Callbacks:</strong> Execute parent functions</li>
        <li><strong>Async Callbacks:</strong> Handle promises from parent</li>
        <li><strong>Transferable Objects:</strong> Efficient ArrayBuffer transfer</li>
        <li><strong>Navigation:</strong> Synchronized routing with parent</li>
        <li><strong>Error Handling:</strong> Proper error propagation</li>
        <li><strong>Cleanup:</strong> Memory leak prevention</li>
      </ul>
    </div>

    <div class="actions">
      <button class="action-btn" @click="handleEmitEvent">
        Emit Custom Event
      </button>
    </div>

    <section class="section">
      <h2>Vue 3 Micro-Frontend</h2>
      <p>
        This application is built as a micro-frontend using Vue 3 and demonstrates
        the power of modern web architecture patterns. It runs independently while
        seamlessly integrating with a host application through a shared SDK.
      </p>
    </section>

    <section class="section">
      <h2>Key Technologies</h2>
      <ul class="tech-list">
        <li>Vue 3 with Composition API</li>
        <li>Vue Router for navigation</li>
        <li>TypeScript for type safety</li>
        <li>Vite for fast development and optimized builds</li>
        <li>Micro-Frontend SDK for host communication</li>
      </ul>
    </section>

    <section class="section">
      <h2>Architecture Benefits</h2>
      <ul class="benefits-list">
        <li><strong>Independent Development:</strong> Teams can work autonomously</li>
        <li><strong>Technology Agnostic:</strong> Mix different frameworks</li>
        <li><strong>Scalability:</strong> Scale teams and features independently</li>
        <li><strong>Deployment:</strong> Deploy micro-apps separately</li>
      </ul>
    </section>

    <section class="section">
      <h2>Settings Page Demonstrations</h2>

      <div class="info-card-demo">
        <h3>About This Demo</h3>
        <p>
          The Settings page demonstrates <strong>Async Callbacks</strong> and <strong>Attribute Listeners</strong>:
        </p>
        <ul>
          <li>Settings can be saved using an async callback function passed from parent</li>
          <li>Theme changes are detected via attribute listeners</li>
          <li>User data updates are synchronized automatically</li>
        </ul>
      </div>

      <div v-if="saveMessage" class="message" :class="{ error: saveMessage.includes('Error') }">
        {{ saveMessage }}
      </div>

      <div class="demo-section-callback">
        <h3>Callback Demo</h3>
        <p>Test synchronous callback functions passed from parent:</p>
        <button class="demo-btn" @click="triggerActionCallback">
          Trigger Action Callback
        </button>
      </div>

      <div class="demo-section-callback">
        <h3>Attribute Listener Demo</h3>
        <p>Request theme change from parent (will trigger attribute listener):</p>
        <div class="theme-demo">
          <div class="theme-indicator" :class="theme">
            Current theme: <strong>{{ theme }}</strong>
          </div>
          <button class="demo-btn" @click="testThemeToggle">
            Request Theme Toggle
          </button>
        </div>
      </div>

      <div class="tech-details">
        <h4>Technical Details</h4>
        <ul>
          <li>
            <strong>Async Callbacks:</strong> saveCallback returns a Promise with result
          </li>
          <li>
            <strong>Attribute Listeners:</strong> onAttr('theme', handler) detects changes
          </li>
          <li>
            <strong>Bidirectional:</strong> Fragment can request changes via events
          </li>
          <li>
            <strong>Type Safety:</strong> TypeScript interfaces ensure correct usage
          </li>
        </ul>
      </div>
    </section>

    <div class="info-box">
      <h3>Application Info</h3>
      <dl class="info-list">
        <dt>Framework:</dt>
        <dd>Vue {{ vueVersion }}</dd>
        <dt>Base Path:</dt>
        <dd>{{ basePath }}</dd>
        <dt>API URL:</dt>
        <dd>{{ apiUrl || 'Not configured' }}</dd>
      </dl>
    </div>
  </PageLayout>
</template>

<style scoped>

.info-card {
  background: #f8f9fa;
  border: 1px solid #dee2e6;
  border-radius: 8px;
  padding: 1.5rem;
  margin-bottom: 2rem;
}

.info-card h3 {
  margin: 0 0 1rem;
  color: #495057;
  font-size: 1.125rem;
}

.info-card pre {
  background: white;
  padding: 1rem;
  border-radius: 4px;
  overflow-x: auto;
  font-size: 0.875rem;
  margin: 0;
}

.features {
  display: grid;
  gap: 1.5rem;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  margin-bottom: 2rem;
}

.feature-card {
  background: white;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
  padding: 1.5rem;
  transition: all 0.2s;
}

.feature-card:hover {
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  transform: translateY(-2px);
}

.feature-icon {
  font-size: 2.5rem;
  margin-bottom: 1rem;
}

.feature-card h3 {
  color: #1a1a1a;
  font-size: 1.25rem;
  margin: 0 0 0.5rem;
}

.feature-card p {
  color: #666;
  line-height: 1.5;
  margin: 0 0 1rem;
}

.feature-link {
  color: #42b883;
  text-decoration: none;
  font-weight: 600;
  transition: color 0.2s;
}

.feature-link:hover {
  color: #35495e;
}

.demo-section {
  background: white;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
  padding: 1.5rem;
  margin-bottom: 2rem;
}

.demo-section h3 {
  margin: 0 0 1rem;
  color: #1a1a1a;
  font-size: 1.25rem;
}

.feature-list {
  margin: 0;
  padding-left: 1.5rem;
  list-style: disc;
}

.feature-list li {
  color: #666;
  line-height: 1.8;
  margin-bottom: 0.5rem;
}

.feature-list strong {
  color: #1a1a1a;
}

.actions {
  display: flex;
  gap: 1rem;
  margin-bottom: 2rem;
}

.action-btn {
  padding: 0.875rem 1.5rem;
  background: #42b883;
  color: white;
  border: none;
  border-radius: 8px;
  cursor: pointer;
  font-size: 0.875rem;
  font-weight: 600;
  transition: background 0.2s;
}

.action-btn:hover {
  background: #35495e;
}

.section {
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
  padding: 1.5rem;
  margin-bottom: 2rem;
}

.section h2 {
  color: #1a1a1a;
  font-size: 1.25rem;
  margin: 0 0 1rem;
}

.section p {
  color: #666;
  line-height: 1.6;
}

.tech-list,
.benefits-list {
  color: #666;
  line-height: 1.8;
  padding-left: 1.5rem;
}

.benefits-list li {
  margin-bottom: 0.5rem;
}

.info-card-demo {
  padding: 1.5rem;
  background: #fef3c7;
  border: 1px solid #fde68a;
  border-radius: 8px;
  margin-bottom: 1.5rem;
}

.info-card-demo h3 {
  margin: 0 0 0.75rem;
  color: #92400e;
  font-size: 1.125rem;
}

.info-card-demo p {
  margin: 0 0 0.5rem;
  color: #78350f;
  line-height: 1.6;
}

.info-card-demo ul {
  margin: 0.5rem 0 0;
  padding-left: 1.5rem;
  color: #78350f;
}

.info-card-demo li {
  margin-bottom: 0.25rem;
}

.message {
  padding: 1rem;
  background: #d1ecf1;
  border: 1px solid #bee5eb;
  border-radius: 6px;
  color: #0c5460;
  font-size: 0.875rem;
  margin-bottom: 1.5rem;
}

.message.error {
  background: #f8d7da;
  border-color: #f5c6cb;
  color: #721c24;
}

.demo-section-callback {
  padding: 1.5rem;
  background: #f9fafb;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
  margin-bottom: 1.5rem;
}

.demo-section-callback h3 {
  margin: 0 0 0.75rem;
  font-size: 1.125rem;
  color: #1a1a1a;
}

.demo-section-callback p {
  margin: 0 0 1rem;
  color: #666;
  font-size: 0.875rem;
}

.demo-btn {
  padding: 0.75rem 1.5rem;
  background: #3b82f6;
  color: white;
  border: none;
  border-radius: 6px;
  cursor: pointer;
  font-size: 0.875rem;
  font-weight: 600;
  transition: background 0.2s;
}

.demo-btn:hover {
  background: #2563eb;
}

.theme-demo {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.theme-indicator {
  padding: 0.75rem 1rem;
  border-radius: 6px;
  font-size: 0.875rem;
}

.theme-indicator.light {
  background: #f9fafb;
  border: 2px solid #e5e7eb;
  color: #1a1a1a;
}

.theme-indicator.dark {
  background: #1f2937;
  border: 2px solid #374151;
  color: #f9fafb;
}

.tech-details {
  padding: 1.5rem;
  background: #f9fafb;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
}

.tech-details h4 {
  margin: 0 0 1rem;
  font-size: 1rem;
  color: #1a1a1a;
}

.tech-details ul {
  margin: 0;
  padding-left: 1.5rem;
  list-style: disc;
}

.tech-details li {
  margin-bottom: 0.5rem;
  color: #666;
  line-height: 1.6;
}

.tech-details li:last-child {
  margin-bottom: 0;
}

.tech-details strong {
  color: #1a1a1a;
}

.info-box {
  background: linear-gradient(135deg, #42b883 0%, #35495e 100%);
  border-radius: 8px;
  color: white;
  padding: 1.5rem;
}

.info-box h3 {
  font-size: 1.25rem;
  margin-bottom: 1rem;
}

.info-list {
  display: grid;
  gap: 0.75rem;
  grid-template-columns: auto 1fr;
}

.info-list dt {
  font-weight: 600;
  opacity: 0.9;
}

.info-list dd {
  margin: 0;
}
</style>
