// apps/app-vue/src/views/Home.vue
<template>
  <div class="view-container">
    <h1 class="title">Welcome to Vue Micro-App</h1>
    <p class="description">
      This is the home page of the Vue 3 micro-frontend application. It demonstrates
      integration with the micro-frontend architecture using the shared SDK.
    </p>
    <div class="features">
      <div class="feature-card">
        <h3>Vue 3</h3>
        <p>Built with the latest Vue 3 Composition API</p>
      </div>
      <div class="feature-card">
        <h3>Vue Router</h3>
        <p>Client-side routing integrated with parent app</p>
      </div>
      <div class="feature-card">
        <h3>Micro-Frontend SDK</h3>
        <p>Seamless communication with the host application</p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { microAppSDK } from '@shared/sdk';

const handleEmitEvent = () => {
  microAppSDK.emit('vue-app-event', { message: 'Hello from Vue!' });
};
</script>

<style scoped>
.view-container {
  max-width: 1200px;
}

.title {
  color: #42b883;
  font-size: 2.5rem;
  margin-bottom: 1rem;
}

.description {
  color: #666;
  font-size: 1.125rem;
  line-height: 1.6;
  margin-bottom: 2rem;
}

.features {
  display: grid;
  gap: 1.5rem;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
}

.feature-card {
  background: white;
  border: 1px solid #e0e0e0;
  border-radius: 8px;
  padding: 1.5rem;
  transition: box-shadow 0.2s;
}

.feature-card:hover {
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
}

.feature-card h3 {
  color: #42b883;
  font-size: 1.25rem;
  margin-bottom: 0.5rem;
}

.feature-card p {
  color: #666;
  line-height: 1.5;
  margin: 0;
}
</style>

// apps/app-solid/src/pages/Home.tsx
import { microAppSDK } from '@micro-fe/fragment-elements/sdk';
import { Component } from 'solid-js';

const Home: Component = () => {
  const handleEmitEvent = () => {
    microAppSDK.emit('user-action', {
      action: 'button-clicked',
      page: 'home',
      timestamp: new Date().toISOString(),
    });
  };

  return (
    <div class="page">
      <h2>Home Page</h2>
      <p>Welcome to the SolidJS micro application!</p>

      <div class="card">
        <h3>About This App</h3>
        <p>
          This is a SolidJS-based micro-frontend application that demonstrates seamless integration
          with the parent application using the Micro App SDK.
        </p>

        <ul>
          <li>Built with SolidJS and TypeScript</li>
          <li>Uses @solidjs/router for routing</li>
          <li>Communicates with parent via postMessage</li>
          <li>Supports dynamic theme and configuration</li>
        </ul>
      </div>

      <div class="card">
        <h3>SDK Integration</h3>
        <p>Click the button below to emit a custom event to the parent application:</p>
        <button onClick={handleEmitEvent} class="btn">
          Emit Custom Event
        </button>
      </div>

      <style>
        {`
          .page {
            max-width: 800px;
            margin: 0 auto;
          }

          .card {
            background: white;
            border-radius: 8px;
            padding: 1.5rem;
            margin: 1.5rem 0;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
          }

          .card h3 {
            margin-top: 0;
            color: #2c7a7b;
          }

          .card ul {
            line-height: 1.8;
          }

          .btn {
            background: #2c7a7b;
            color: white;
            border: none;
            padding: 0.75rem 1.5rem;
            border-radius: 4px;
            cursor: pointer;
            font-size: 1rem;
            transition: background-color 0.2s;
          }

          .btn:hover {
            background: #234e52;
          }

          .btn:active {
            transform: translateY(1px);
          }
        `}
      </style>
    </div>
  );
};

export default Home;
