// apps/app-vue/src/App.vue
<template>
  <div id="app" class="app-container">
    <nav class="navigation">
      <ul class="nav-menu">
        <li class="nav-item">
          <router-link class="nav-link" to="/">Home</router-link>
        </li>
        <li class="nav-item">
          <router-link class="nav-link" to="/about">About</router-link>
        </li>
        <li class="nav-item">
          <router-link class="nav-link" to="/contact">Contact</router-link>
        </li>
      </ul>
    </nav>

    <main class="main-content">
      <router-view />
    </main>
  </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue';
import { microAppSDK } from '@shared/sdk';

onMounted(() => {
  console.log('Vue micro-app mounted');
  console.log('Config:', microAppSDK.getConfig());
});
</script>

<style scoped>
.app-container {
  display: flex;
  flex-direction: column;
  font-family: system-ui, -apple-system, sans-serif;
  height: 100%;
  min-height: 100vh;
}

.navigation {
  background-color: #42b883;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  padding: 1rem;
}

.nav-menu {
  align-items: center;
  display: flex;
  gap: 2rem;
  list-style: none;
  margin: 0;
  padding: 0;
}

.nav-item {
  margin: 0;
}

.nav-link {
  color: white;
  font-weight: 600;
  padding: 0.5rem 1rem;
  text-decoration: none;
  transition: background-color 0.2s;
}

.nav-link:hover {
  background-color: rgba(255, 255, 255, 0.1);
  border-radius: 4px;
}

.nav-link.router-link-active {
  background-color: rgba(255, 255, 255, 0.2);
  border-radius: 4px;
}

.main-content {
  flex: 1;
  padding: 2rem;
}
</style>

// apps/app-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { microAppSDK } from '@shared/sdk';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterLink, RouterLinkActive, RouterOutlet],
  template: `
    <div class="app-container">
      <nav class="navigation">
        <h2>Angular Micro-App</h2>
        <ul>
          <li>
            <a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }">
              Home
            </a>
          </li>
          <li>
            <a routerLink="/users" routerLinkActive="active">
              Users
            </a>
          </li>
          <li>
            <a routerLink="/settings" routerLinkActive="active">
              Settings
            </a>
          </li>
        </ul>
      </nav>

      <main class="content">
        <router-outlet />
      </main>
    </div>
  `,
  styles: [
    `
      .app-container {
        display: flex;
        flex-direction: column;
        height: 100vh;
        font-family: system-ui, -apple-system, sans-serif;
      }

      .navigation {
        background: #2c3e50;
        color: white;
        padding: 1rem 2rem;
      }

      .navigation h2 {
        margin: 0 0 1rem 0;
        font-size: 1.25rem;
      }

      .navigation ul {
        list-style: none;
        padding: 0;
        margin: 0;
        display: flex;
        gap: 1.5rem;
      }

      .navigation a {
        color: #ecf0f1;
        text-decoration: none;
        padding: 0.5rem 1rem;
        border-radius: 4px;
        transition: background-color 0.2s;
      }

      .navigation a:hover {
        background-color: #34495e;
      }

      .navigation a.active {
        background-color: #3498db;
      }

      .content {
        flex: 1;
        padding: 2rem;
        overflow-y: auto;
      }
    `,
  ],
})
export class AppComponent {
  constructor() {
    const config = microAppSDK.getConfig();
    console.log('Angular App Component initialized with config:', config);
  }
}

<div id="app" class="app-container" [ngClass]="theme">
  <nav class="navigation">
    <ul class="nav-menu">
      <li class="nav-item">
        <a class="nav-link" routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }">
          Home
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" routerLink="/tasks" routerLinkActive="active">
          Tasks
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" routerLink="/analytics" routerLinkActive="active">
          Analytics
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" routerLink="/settings" routerLinkActive="active">
          Settings
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" routerLink="/about" routerLinkActive="active">
          About
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" routerLink="/contact" routerLinkActive="active">
          Contact
        </a>
      </li>
      <li class="nav-item">
        <button class="demo-btn" (click)="triggerAction()">
          Test Action
        </button>
      </li>
      <li class="nav-item">
        <button class="demo-btn error-btn" (click)="triggerError()">
          Test Error
        </button>
      </li>
    </ul>
  </nav>

  <main class="main-content">
    <router-outlet></router-outlet>
  </main>
</div>
