// apps/app-shell/src/app/app.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule, NavigationEnd } from '@angular/router';
import { filter } from 'rxjs/operators';

interface MicroAppConfig {
  baseUrl: string;
  name: string;
  port: number;
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterModule],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <div class="app-shell">
      <header class="header">
        <h1>Micro Frontend App Shell</h1>
        <nav class="nav">
          <a
            *ngFor="let app of apps"
            [routerLink]="['/' + app.name]"
            routerLinkActive="active"
            class="nav-link"
          >
            {{ app.name | titlecase }}
          </a>
        </nav>
      </header>

      <main class="main">
        <fragment-frame
          *ngIf="activeApp === 'angular'"
          name="angular"
          [url]="getMicroAppUrl('angular')"
          (ready)="onMicroAppReady($event)"
          (navigate)="onMicroAppNavigate($event)"
          (error)="onMicroAppError($event)"
        ></fragment-frame>

        <fragment-frame
          *ngIf="activeApp === 'vue'"
          name="vue"
          [url]="getMicroAppUrl('vue')"
          (ready)="onMicroAppReady($event)"
          (navigate)="onMicroAppNavigate($event)"
          (error)="onMicroAppError($event)"
        ></fragment-frame>

        <fragment-frame
          *ngIf="activeApp === 'react'"
          name="react"
          [url]="getMicroAppUrl('react')"
          (ready)="onMicroAppReady($event)"
          (navigate)="onMicroAppNavigate($event)"
          (error)="onMicroAppError($event)"
        ></fragment-frame>

        <fragment-frame
          *ngIf="activeApp === 'solid'"
          name="solid"
          [url]="getMicroAppUrl('solid')"
          (ready)="onMicroAppReady($event)"
          (navigate)="onMicroAppNavigate($event)"
          (error)="onMicroAppError($event)"
        ></fragment-frame>
      </main>
    </div>
  `,
  styles: [`
    .app-shell {
      display: flex;
      flex-direction: column;
      height: 100vh;
    }

    .header {
      background: #1976d2;
      color: white;
      padding: 1rem 2rem;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }

    .header h1 {
      margin: 0 0 1rem 0;
      font-size: 1.5rem;
    }

    .nav {
      display: flex;
      gap: 1rem;
    }

    .nav-link {
      color: white;
      text-decoration: none;
      padding: 0.5rem 1rem;
      border-radius: 4px;
      transition: background-color 0.2s;
    }

    .nav-link:hover {
      background-color: rgba(255, 255, 255, 0.1);
    }

    .nav-link.active {
      background-color: rgba(255, 255, 255, 0.2);
      font-weight: bold;
    }

    .main {
      flex: 1;
      overflow: hidden;
      position: relative;
    }

    fragment-frame {
      display: block;
      width: 100%;
      height: 100%;
    }
  `]
})
export class AppComponent implements OnInit {
  activeApp: string = '';

  apps: MicroAppConfig[] = [
    { name: 'angular', baseUrl: 'http://localhost', port: 4201 },
    { name: 'vue', baseUrl: 'http://localhost', port: 4202 },
    { name: 'react', baseUrl: 'http://localhost', port: 4203 },
    { name: 'solid', baseUrl: 'http://localhost', port: 4204 }
  ];

  private microAppElements = new Map<string, HTMLElement>();

  constructor(private router: Router) {}

  ngOnInit() {
    // Listen to router navigation events
    this.router.events
      .pipe(filter(event => event instanceof NavigationEnd))
      .subscribe((event: NavigationEnd) => {
        this.updateActiveApp(event.urlAfterRedirects);
      });

    // Set initial active app
    this.updateActiveApp(this.router.url);
  }

  getMicroAppUrl(appName: string): string {
    const app = this.apps.find(a => a.name === appName);
    return app ? `${app.baseUrl}:${app.port}` : '';
  }

  onMicroAppReady(event: Event) {
    const customEvent = event as CustomEvent;
    const { name } = customEvent.detail;

    console.log(`Micro-app ${name} is ready`);

    // Store reference to fragment-frame element
    const element = event.target as HTMLElement;
    this.microAppElements.set(name, element);

    // Sync current route to the fragment-frame
    this.syncRouteToMicroApp(name);
  }

  onMicroAppNavigate(event: Event) {
    const customEvent = event as CustomEvent;
    const { name, path } = customEvent.detail;

    console.log(`Navigation from ${name}: ${path}`);

    // Update browser URL when fragment-frame navigates
    const newUrl = `/${name}${path}`;

    // Only navigate if the URL is different
    if (this.router.url !== newUrl) {
      this.router.navigateByUrl(newUrl);
    }
  }

  onMicroAppError(event: Event) {
    const customEvent = event as CustomEvent;
    const { name, error } = customEvent.detail;

    console.error(`Error from ${name}:`, error);

    // You could show a user-friendly error message here
    alert(`Error loading ${name} fragment-frame: ${error}`);
  }

  private updateActiveApp(url: string) {
    // Extract the first segment of the URL
    const segments = url.split('/').filter(s => s.length > 0);
    const firstSegment = segments[0] || 'angular';

    // Check if it matches any of our apps
    const app = this.apps.find(a => a.name === firstSegment);

    if (app) {
      this.activeApp = app.name;

      // Sync route to the newly activated fragment-frame after a short delay
      // to ensure the element is rendered
      setTimeout(() => {
        this.syncRouteToMicroApp(app.name);
      }, 100);
    }
  }

  private syncRouteToMicroApp(appName: string) {
    const element = this.microAppElements.get(appName);

    if (!element) {
      return;
    }

    // Extract the path within the fragment-frame
    const currentUrl = this.router.url;
    const appPath = currentUrl.replace(`/${appName}`, '') || '/';

    // Send navigation message to the fragment-frame
    const iframe = element.querySelector('iframe');

    if (iframe && iframe.contentWindow) {
      iframe.contentWindow.postMessage({
        type: 'navigate',
        path: appPath
      }, '*');
    }
  }
}

// apps/shell-vue/src/App.vue
<template>
  <div class="app-shell">
    <header class="header">
      <h1>Micro Frontend Shell (Vue)</h1>
      <nav class="nav">
        <router-link
          v-for="app in apps"
          :key="app.name"
          :to="`/${app.name}`"
          class="nav-link"
          :class="{ active: activeApp === app.name }"
        >
          {{ app.name.charAt(0).toUpperCase() + app.name.slice(1) }}
        </router-link>
        <button class="theme-toggle" @click="toggleTheme">
          Toggle Theme ({{ currentTheme }})
        </button>
      </nav>
    </header>

    <main class="main">
      <!-- Angular Fragment -->
      <fragment-frame
        v-if="activeApp === 'angular'"
        ref="angularFrame"
        :user="currentUser"
        :theme="currentTheme"
        :successCallback="handleAngularSuccess"
        :actionCallback="handleAngularAction"
        @ready="onFrameReady"
        @navigate="onFrameNavigate"
        @error="onFrameError"
        @action-clicked="onActionClicked"
      />

      <!-- Vue Fragment -->
      <fragment-frame
        v-if="activeApp === 'vue'"
        ref="vueFrame"
        :theme="currentTheme"
        @ready="onFrameReady"
        @navigate="onFrameNavigate"
        @error="onFrameError"
        @counter-changed="onCounterChanged"
      />

      <!-- React Fragment -->
      <fragment-frame
        v-if="activeApp === 'react'"
        ref="reactFrame"
        base="/react"
        :metricsData="metricsArrayBuffer"
        :fetchDataCallback="handleFetchData"
        @ready="onFrameReady"
        @navigate="onFrameNavigate"
        @error="onFrameError"
        @data-loaded="onDataLoaded"
        @large-data="onLargeData"
      />

    </main>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted, watchEffect } from 'vue';
import { useRoute, useRouter } from 'vue-router';

interface FrameConfig {
  baseUrl: string;
  name: string;
  port: number;
}

const route = useRoute();
const router = useRouter();

// Refs to fragment-frame elements
const angularFrame = ref<HTMLElement | null>(null);
const vueFrame = ref<HTMLElement | null>(null);
const reactFrame = ref<HTMLElement | null>(null);

// Apps configuration
const apps: FrameConfig[] = [
  { name: 'angular', baseUrl: 'http://localhost', port: 4201 },
  { name: 'vue', baseUrl: 'http://localhost', port: 4202 },
  { name: 'react', baseUrl: 'http://localhost', port: 4203 }
];

// Current active app
const activeApp = computed(() => {
  const path = route.path;
  for (const app of apps) {
    if (path.startsWith(`/${app.name}`)) {
      return app.name;
    }
  }
  return 'angular'; // default
});

// Props for Angular (Callbacks + Error handling)
const currentUser = ref({
  id: 1,
  name: 'John Doe',
  role: 'admin',
  email: 'john@example.com'
});

// Props for Vue and Angular (Reactivity)
const currentTheme = ref<'light' | 'dark'>('light');

// Props for React (Transferable Objects)
const metricsArrayBuffer = ref<ArrayBuffer>(new ArrayBuffer(0));


// Frame elements map
const frameElements = new Map<string, HTMLElement>();

// Callbacks for Angular
const handleAngularSuccess = (data: any) => {
  console.log('[Shell] Angular success callback received:', data);
};

const handleAngularAction = (data: any) => {
  console.log('[Shell] Angular action callback received:', data);
};

// Callback for React (Async function)
const handleFetchData = async (params: any) => {
  console.log('[Shell] Fetching data with params:', params);

  // Simulate API call
  await new Promise(resolve => setTimeout(resolve, 1000));

  return {
    query: params.query,
    results: [
      { id: 1, title: 'Result 1', description: 'Data from parent' },
      { id: 2, title: 'Result 2', description: 'Async callback demo' },
    ],
    timestamp: Date.now()
  };
};

// Get frame URL
const getFrameUrl = (appName: string): string => {
  const app = apps.find(a => a.name === appName);
  if (!app) return '';

  const basePath = appName === 'vue' ? '/vue/' :
                   appName === 'react' ? '/react/' :
                   appName === 'solid' ? '/solid/' : '/';

  return `${app.baseUrl}:${app.port}${basePath}`;
};

// Toggle theme
const toggleTheme = () => {
  currentTheme.value = currentTheme.value === 'light' ? 'dark' : 'light';
  console.log('[Shell] Theme toggled to:', currentTheme.value);
};

// Event handlers
const onFrameReady = (event: CustomEvent) => {
  const { name } = event.detail;
  console.log(`[Shell] Fragment '${name}' is ready`);

  // Store reference to fragment-frame element
  const frameElement = event.target as HTMLElement;
  frameElements.set(name, frameElement);

  // Sync current route to the fragment-frame
  syncRouteToFrame(name);
};

const onFrameNavigate = (event: CustomEvent) => {
  const { path } = event.detail;
  const frameName = (event.target as any).getAttribute('name');

  console.log(`[Shell] Fragment '${frameName}' navigated to:`, path);

  // Update browser URL when fragment-frame navigates
  const fullPath = `/${frameName}${path}`;
  if (route.path !== fullPath) {
    router.push(fullPath);
  }
};

const onFrameError = (event: CustomEvent) => {
  const { error, message } = event.detail;
  const frameName = (event.target as any).getAttribute('name');
  console.error(`[Shell] Error from fragment '${frameName}':`, message || error);
};

const onActionClicked = (event: CustomEvent) => {
  console.log('[Shell] Action clicked event:', event.detail);
};

const onCounterChanged = (event: CustomEvent) => {
  console.log('[Shell] Counter changed:', event.detail);
};

const onDataLoaded = (event: CustomEvent) => {
  console.log('[Shell] Data loaded:', event.detail);
};

const onLargeData = (event: CustomEvent) => {
  console.log('[Shell] Large data received:', event.detail);
};


// Sync route to the newly activated fragment-frame
const syncRouteToFrame = (frameName: string) => {
  const frameElement = frameElements.get(frameName);
  if (!frameElement) return;

  // Extract the path within the fragment-frame
  const fullPath = route.path;
  const fragmentPath = fullPath.replace(`/${frameName}`, '') || '/';

  console.log(`[Shell] Syncing route to ${frameName}:`, fragmentPath);

  // Send navigation message to the fragment-frame
  // This will be handled by the fragment's SDK
  (frameElement as any).emitToChild?.('route-change', {
    path: fragmentPath,
    replace: false
  });
};

// Watch for route changes
watch(() => route.path, () => {
  // Sync route to the frame after it changes
  setTimeout(() => {
    syncRouteToFrame(activeApp.value);
  }, 100);
});

// Set attributes on fragment-frame elements
watchEffect(() => {
  if (angularFrame.value) {
    angularFrame.value.setAttribute('name', 'angular');
    angularFrame.value.setAttribute('src', getFrameUrl('angular'));
  }
  if (vueFrame.value) {
    vueFrame.value.setAttribute('name', 'vue');
    vueFrame.value.setAttribute('src', getFrameUrl('vue'));
  }
  if (reactFrame.value) {
    reactFrame.value.setAttribute('name', 'react');
    reactFrame.value.setAttribute('src', getFrameUrl('react'));
  }
});

// Initialize metrics ArrayBuffer for React
onMounted(() => {
  const buffer = new ArrayBuffer(16);
  const view = new DataView(buffer);
  view.setFloat64(0, Math.random() * 1000); // metric1
  view.setFloat64(8, Math.random() * 100);  // metric2
  metricsArrayBuffer.value = buffer;
});
</script>

<style scoped>
.app-shell {
  display: flex;
  flex-direction: column;
  height: 100vh;
  font-family: system-ui, -apple-system, sans-serif;
}

.header {
  background: #1e293b;
  color: white;
  padding: 1rem 2rem;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.header h1 {
  margin: 0 0 1rem 0;
  font-size: 1.5rem;
}

.nav {
  display: flex;
  gap: 1rem;
  align-items: center;
}

.nav-link {
  color: #94a3b8;
  text-decoration: none;
  padding: 0.5rem 1rem;
  border-radius: 4px;
  transition: all 0.2s;
}

.nav-link:hover {
  background: #334155;
  color: white;
}

.nav-link.active {
  background: #3b82f6;
  color: white;
}

.theme-toggle {
  margin-left: auto;
  padding: 0.5rem 1rem;
  background: #3b82f6;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 0.875rem;
}

.theme-toggle:hover {
  background: #2563eb;
}

.main {
  flex: 1;
  overflow: hidden;
}

fragment-frame {
  display: block;
  width: 100%;
  height: 100%;
}
</style>
