// apps/app-react/src/main.tsx
import { frameSDK } from "@zomme/fragment-frame-react";
import React from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import App from "./App";
import "./App.css";

async function bootstrap() {
  let base = "/react";
  let sdkAvailable = false;

  try {
    await frameSDK.initialize();
    base = frameSDK.props.base || "/react";
    sdkAvailable = true;

    console.log("FrameSDK initialized successfully");
  } catch (error) {
    console.warn("FrameSDK not available, running in standalone mode:", error);
    sdkAvailable = false;
  }

  const rootElement = document.getElementById("root");
  if (!rootElement) {
    throw new Error("Root element not found");
  }

  const root = createRoot(rootElement);
  root.render(
    <React.StrictMode>
      <BrowserRouter basename={base}>
        <App sdkAvailable={sdkAvailable} base={base} />
      </BrowserRouter>
    </React.StrictMode>,
  );

  console.log(`React app rendered with base: ${base} (SDK available: ${sdkAvailable})`);
}

bootstrap().catch((error) => {
  console.error("Failed to bootstrap React micro app:", error);
});

// apps/app-solid/src/index.tsx
/* @refresh reload */
import { Router } from '@solidjs/router';
import { microAppSDK } from '@micro-fe/fragment-elements/sdk';
import { render } from 'solid-js/web';
import App from './App';
import './styles.css';

const base = '/solid';

async function bootstrap() {
  try {
    await microAppSDK.initialize();

    const config = microAppSDK.getConfig();
    console.log('[SolidJS] Micro app initialized with config:', config);

    const root = document.getElementById('root');

    if (!root) {
      throw new Error('Root element not found');
    }

    render(
      () => (
        <Router base={base}>
          <App />
        </Router>
      ),
      root
    );

    console.log('[SolidJS] App rendered successfully');
  } catch (error) {
    console.error('[SolidJS] Failed to initialize micro app:', error);
    microAppSDK.reportError(error instanceof Error ? error : new Error(String(error)));
  }
}

bootstrap();
