// packages/frame-react/src/Frame.tsx
import "@zomme/frame";
import React, { useEffect, useRef } from "react";

interface FrameProps {
  /** Name of the frame (used for identification) */
  name: string;

  /** URL to load in the iframe */
  src: string;

  /** Sandbox permissions for the iframe */
  sandbox?: string;

  /** Optional HTML attributes */
  className?: string;
  style?: React.CSSProperties;
  id?: string;

  /** Event handlers for z-frame events */
  onReady?: (event: CustomEvent) => void;
  onNavigate?: (event: CustomEvent) => void;
  onError?: (event: CustomEvent) => void;

  /** Props to pass to the child frame (serialized automatically) */
  [key: string]: unknown;
}

/**
 * React component wrapper for <z-frame> custom element
 *
 * @example
 * ```tsx
 * <Frame
 *   name="my-app"
 *   src="http://localhost:3000/"
 *   user={{ id: 1, name: "John" }}
 *   theme="dark"
 *   onReady={(e) => console.log('Ready:', e.detail)}
 *   onNavigate={(e) => console.log('Navigate:', e.detail)}
 * />
 * ```
 */
export const Frame = React.forwardRef<HTMLElement, FrameProps>(
  (
    {
      name,
      src,
      sandbox = "allow-scripts allow-same-origin",
      onReady,
      onNavigate,
      onError,
      ...props
    },
    ref,
  ) => {
    const elementRef = useRef<HTMLElement>(null);

    useEffect(() => {
      const element = elementRef.current;
      if (!element) return;

      // Set up event listeners
      const listeners: Array<[string, EventListener]> = [];

      if (onReady) {
        const handler = onReady as EventListener;
        element.addEventListener("ready", handler);
        listeners.push(["ready", handler]);
      }

      if (onNavigate) {
        const handler = onNavigate as EventListener;
        element.addEventListener("navigate", handler);
        listeners.push(["navigate", handler]);
      }

      if (onError) {
        const handler = onError as EventListener;
        element.addEventListener("error", handler);
        listeners.push(["error", handler]);
      }

      // Handle custom event handlers (on*)
      Object.entries(props).forEach(([key, value]) => {
        if (
          key.startsWith("on") &&
          typeof value === "function" &&
          key !== "onReady" &&
          key !== "onNavigate" &&
          key !== "onError"
        ) {
          const eventName = key.slice(2).toLowerCase();
          const handler = value as EventListener;
          element.addEventListener(eventName, handler);
          listeners.push([eventName, handler]);
        }
      });

      return () => {
        listeners.forEach(([event, handler]) => {
          element.removeEventListener(event, handler);
        });
      };
    }, [onReady, onNavigate, onError, props]);

    useEffect(() => {
      const element = elementRef.current;
      if (!element) return;

      // Set props as properties (for complex objects, functions, etc.)
      Object.entries(props).forEach(([key, value]) => {
        // Skip event handlers and standard HTML attributes
        if (key.startsWith("on") || ["className", "style", "id"].includes(key)) return;

        // Set as property for complex types
        (element as any)[key] = value;
      });
    }, [props]);

    return React.createElement("z-frame", {
      ref: (el: HTMLElement | null) => {
        (elementRef as React.MutableRefObject<HTMLElement | null>).current = el;
        if (typeof ref === "function") {
          ref(el);
        } else if (ref) {
          ref.current = el;
        }
      },
      name,
      src,
      sandbox,
      ...Object.fromEntries(
        Object.entries(props).filter(
          ([key]) => !key.startsWith("on") && ["className", "style", "id"].includes(key),
        ),
      ),
    });
  },
);

Frame.displayName = "Frame";

// packages/frame-angular/src/frame.component.ts
import "@zomme/frame";
import {
  Component,
  type ElementRef,
  EventEmitter,
  Input,
  type OnChanges,
  type OnDestroy,
  type OnInit,
  Output,
  type SimpleChanges,
  ViewChild,
} from "@angular/core";

/**
 * Angular component wrapper for <z-frame> custom element
 *
 * @example
 * ```ts
 * \@Component({
 *   template: `
 *     <frame-component
 *       name="my-app"
 *       src="http://localhost:3000/"
 *       [user]="{ id: 1, name: 'John' }"
 *       theme="dark"
 *       (ready)="onReady($event)"
 *       (navigate)="onNavigate($event)"
 *     />
 *   `
 * })
 * export class MyComponent {
 *   onReady(event: CustomEvent) {
 *     console.log('Ready:', event.detail);
 *   }
 *
 *   onNavigate(event: CustomEvent) {
 *     console.log('Navigate:', event.detail);
 *   }
 * }
 * ```
 */
@Component({
  selector: "frame-component",
  standalone: true,
  template: `
    <z-frame
      #frameElement
      [attr.name]="name"
      [attr.src]="src"
      [attr.sandbox]="sandbox"
    ></z-frame>
  `,
  styles: [
    `
      :host {
        display: block;
        width: 100%;
        height: 100%;
      }

      z-frame {
        display: block;
        width: 100%;
        height: 100%;
      }
    `,
  ],
})
export class FrameComponent implements OnInit, OnChanges, OnDestroy {
  @ViewChild("frameElement", { static: true }) frameElement!: ElementRef<HTMLElement>;

  /** Name of the frame (used for identification) */
  @Input() name!: string;

  /** URL to load in the iframe */
  @Input() src!: string;

  /** Sandbox permissions for the iframe */
  @Input() sandbox = "allow-scripts allow-same-origin";

  /** Props to pass to the child frame (any complex objects) */
  @Input() props: Record<string, unknown> = {};

  /** Ready event - emitted when frame is initialized */
  @Output() ready = new EventEmitter<CustomEvent>();

  /** Navigate event - emitted when frame navigates */
  @Output() navigate = new EventEmitter<CustomEvent>();

  /** Error event - emitted when frame encounters error */
  @Output() error = new EventEmitter<CustomEvent>();

  private eventListeners: Array<[string, EventListener]> = [];

  ngOnInit(): void {
    const element = this.frameElement.nativeElement;

    // Setup event listeners
    this.addListener("ready", (event) => this.ready.emit(event as CustomEvent));
    this.addListener("navigate", (event) => this.navigate.emit(event as CustomEvent));
    this.addListener("error", (event) => this.error.emit(event as CustomEvent));

    // Set initial props
    this.updateProps();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes["props"] && !changes["props"].firstChange) {
      this.updateProps();
    }
  }

  ngOnDestroy(): void {
    // Clean up event listeners
    const element = this.frameElement.nativeElement;
    this.eventListeners.forEach(([event, handler]) => {
      element.removeEventListener(event, handler);
    });
    this.eventListeners = [];
  }

  private addListener(eventName: string, handler: EventListener): void {
    const element = this.frameElement.nativeElement;
    element.addEventListener(eventName, handler);
    this.eventListeners.push([eventName, handler]);
  }

  private updateProps(): void {
    const element = this.frameElement.nativeElement;
    Object.entries(this.props).forEach(([key, value]) => {
      (element as any)[key] = value;
    });
  }
}
