// packages/fragment-frame-angular/src/fragment-frame.component.ts
import "@zomme/fragment-frame";
import {
  Component,
  ElementRef,
  EventEmitter,
  Input,
  OnChanges,
  OnDestroy,
  OnInit,
  Output,
  SimpleChanges,
  ViewChild,
} from "@angular/core";

/**
 * Angular component wrapper for <fragment-frame> custom element
 *
 * @example
 * ```ts
 * \@Component({
 *   template: `
 *     <fragment-frame-component
 *       name="my-app"
 *       src="http://localhost:3000/"
 *       [user]="{ id: 1, name: 'John' }"
 *       theme="dark"
 *       (ready)="onReady($event)"
 *       (navigate)="onNavigate($event)"
 *     />
 *   `
 * })
 * export class MyComponent {
 *   onReady(event: CustomEvent) {
 *     console.log('Ready:', event.detail);
 *   }
 *
 *   onNavigate(event: CustomEvent) {
 *     console.log('Navigate:', event.detail);
 *   }
 * }
 * ```
 */
@Component({
  selector: "fragment-frame-component",
  standalone: true,
  template: `
    <fragment-frame
      #frameElement
      [attr.name]="name"
      [attr.src]="src"
      [attr.sandbox]="sandbox"
    ></fragment-frame>
  `,
  styles: [
    `
      :host {
        display: block;
        width: 100%;
        height: 100%;
      }

      fragment-frame {
        display: block;
        width: 100%;
        height: 100%;
      }
    `,
  ],
})
export class FragmentFrameComponent implements OnInit, OnChanges, OnDestroy {
  @ViewChild("frameElement", { static: true }) frameElement!: ElementRef<HTMLElement>;

  /** Name of the fragment (used for identification) */
  @Input() name!: string;

  /** URL to load in the iframe */
  @Input() src!: string;

  /** Sandbox permissions for the iframe */
  @Input() sandbox = "allow-scripts allow-same-origin";

  /** Props to pass to the child frame (any complex objects) */
  @Input() props: Record<string, unknown> = {};

  /** Ready event - emitted when frame is initialized */
  @Output() ready = new EventEmitter<CustomEvent>();

  /** Navigate event - emitted when frame navigates */
  @Output() navigate = new EventEmitter<CustomEvent>();

  /** Error event - emitted when frame encounters error */
  @Output() error = new EventEmitter<CustomEvent>();

  private eventListeners: Array<[string, EventListener]> = [];

  ngOnInit(): void {
    const element = this.frameElement.nativeElement;

    // Setup event listeners
    this.addListener("ready", (event) => this.ready.emit(event as CustomEvent));
    this.addListener("navigate", (event) => this.navigate.emit(event as CustomEvent));
    this.addListener("error", (event) => this.error.emit(event as CustomEvent));

    // Set initial props
    this.updateProps();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes["props"] && !changes["props"].firstChange) {
      this.updateProps();
    }
  }

  ngOnDestroy(): void {
    // Clean up event listeners
    const element = this.frameElement.nativeElement;
    this.eventListeners.forEach(([event, handler]) => {
      element.removeEventListener(event, handler);
    });
    this.eventListeners = [];
  }

  private addListener(eventName: string, handler: EventListener): void {
    const element = this.frameElement.nativeElement;
    element.addEventListener(eventName, handler);
    this.eventListeners.push([eventName, handler]);
  }

  private updateProps(): void {
    const element = this.frameElement.nativeElement;
    Object.entries(this.props).forEach(([key, value]) => {
      (element as any)[key] = value;
    });
  }
}

// packages/fragment-frame-vue/src/FragmentFrame.vue
<script setup lang="ts">
import "@zomme/fragment-frame";
import { onMounted, onUnmounted, ref, watch } from "vue";

interface Props {
  /** Name of the fragment (used for identification) */
  name: string;

  /** URL to load in the iframe */
  src: string;

  /** Sandbox permissions for the iframe */
  sandbox?: string;

  /** Props to pass to the child frame (any complex objects) */
  [key: string]: unknown;
}

const props = withDefaults(defineProps<Props>(), {
  sandbox: "allow-scripts allow-same-origin",
});

const emit = defineEmits<{
  ready: [event: CustomEvent];
  navigate: [event: CustomEvent];
  error: [event: CustomEvent];
  [key: string]: [event: CustomEvent];
}>();

const elementRef = ref<HTMLElement>();
const eventListeners: Array<[string, EventListener]> = [];

onMounted(() => {
  const element = elementRef.value;
  if (!element) return;

  // Set props as properties on the custom element
  Object.entries(props).forEach(([key, value]) => {
    if (!["name", "src", "sandbox"].includes(key)) {
      (element as any)[key] = value;
    }
  });

  // Setup event listeners
  const addListener = (eventName: string, emitName: string) => {
    const handler = (event: Event) => emit(emitName, event as CustomEvent);
    element.addEventListener(eventName, handler);
    eventListeners.push([eventName, handler]);
  };

  addListener("ready", "ready");
  addListener("navigate", "navigate");
  addListener("error", "error");
});

onUnmounted(() => {
  const element = elementRef.value;
  if (!element) return;

  // Clean up all event listeners
  eventListeners.forEach(([event, handler]) => {
    element.removeEventListener(event, handler);
  });
  eventListeners.length = 0;
});

// Watch for prop changes and update element properties
watch(
  () => props,
  (newProps) => {
    const element = elementRef.value;
    if (!element) return;

    Object.entries(newProps).forEach(([key, value]) => {
      if (!["name", "src", "sandbox"].includes(key)) {
        (element as any)[key] = value;
      }
    });
  },
  { deep: true }
);
</script>

<template>
  <fragment-frame
    ref="elementRef"
    :name="name"
    :src="src"
    :sandbox="sandbox"
  />
</template>
