// apps/app-vue/src/components/PageLayout.vue
<script setup lang="ts">
interface Props {
  subtitle?: string;
  title: string;
}

defineProps<Props>();
</script>

<template>
  <div class="page-layout">
    <div class="header">
      <h1>{{ title }}</h1>
      <p v-if="subtitle" class="subtitle">{{ subtitle }}</p>
    </div>

    <div class="content">
      <slot />
    </div>
  </div>
</template>

<style scoped>
.page-layout {
  padding: 2rem;
  max-width: 1200px;
  margin: 0 auto;
}

.header {
  margin-bottom: 2rem;
}

.header h1 {
  margin: 0;
  font-size: 2rem;
  color: #1a1a1a;
}

.subtitle {
  margin: 0.5rem 0 0;
  color: #666;
  font-size: 0.875rem;
}

.content {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}
</style>

// apps/app-react/src/components/PageLayout.tsx
import type { CSSProperties, ReactNode } from "react";

interface PageLayoutProps {
  children: ReactNode;
  subtitle?: string;
  title: string;
}

export function PageLayout({ children, subtitle, title }: PageLayoutProps) {
  const styles: Record<string, CSSProperties> = {
    pageLayout: {
      padding: "2rem",
      maxWidth: "1200px",
      margin: "0 auto",
    },
    header: {
      marginBottom: "2rem",
    },
    title: {
      margin: 0,
      fontSize: "2rem",
      color: "#1a1a1a",
    },
    subtitle: {
      margin: "0.5rem 0 0",
      color: "#666",
      fontSize: "0.875rem",
    },
    content: {
      display: "flex",
      flexDirection: "column" as const,
      gap: "1.5rem",
    },
  };

  return (
    <div style={styles.pageLayout}>
      <div style={styles.header}>
        <h1 style={styles.title}>{title}</h1>
        {subtitle && <p style={styles.subtitle}>{subtitle}</p>}
      </div>

      <div style={styles.content}>{children}</div>
    </div>
  );
}
